### ISSUE TITLE
Allow noqa of block statement

### ISSUE THREAD

**Issue by addisonlynch** [kataev/flake8-rst#15]
Consider:

```python
%prun -l 4 df.apply(lambda x: integrate_f(x['a'], x['b'], x['N']), axis=1)  
```

Wish to ``noqa`` the syntax error caused by ``%prun -l 4``, but the line is too long when the ``noqa`` is added. But if we try:

```python
%prun -l 4 df.apply(lambda x: integrate_f(x['a'],
                                          x['b'],
                                          x['N']),
                    axis=1)  # noqa: E999
```

we are still met with ``E599`` from ``%prun -l 4``

**Comment by FHaase** [comment]
I've created PR #16 which should fix throwing syntax errors when using the `%prun` magic.

In order to `noqa` a complete block you can use the `:flake8-group: Ignore` role. Then the `code-block` won't be passed to `flake8`.

**Comment by kataev** [comment]
Merged. Also 0.7.1 released.
