### ISSUE TITLE
project maintenance

### ISSUE THREAD

**Issue by MarcoGorelli** [kataev/flake8-rst#30]
Hi @kataev 

Do you still plan to maintain this project? If not, have you considered handing maintenance over?

Thanks

**Comment by tgross35** [comment]
Seems like this project has been pretty well abandoned for 2 years.

@asottile have you considered something like this project to accompany blacken-docs? You could fork it to PyCQA or your namespace and open up contributions to get it up to date. `flake8-docs` is available on PyPi.

**Comment by tgross35** [comment]
I emailed the maintainer to see if there's any luck there

**Comment by kataev** [comment]
Okay, np. Did you know how i can do it?

**Comment by tgross35** [comment]
Thanks for getting back. First we find you a good maintainer:)

Let's see what asottile says. He runs flake8 itself and stuff like pre-commit, so if he could get involved that's would definitely be best

**Comment by asottile** [comment]
I don't use rst nor do I have any bandwidth to maintain another thing -- additionally flake8 is only intended to lint python files so flake8-rst doesn't really make sense as it is

**Comment by tgross35** [comment]
Ok, there's our answer. Thanks Anthony.

MarcoGorelli seems pretty active and might be a good choice.

**Comment by tgross35** [comment]
Alright, this is all sorted out now as we're now under a new organization, with Marco and Denis as maintainers.
